### ISSUE TITLE
Creación de metas

### ISSUE THREAD

**Issue by lizethcorrales** [jose-andres-ucr/nutrimetas#1]
**Yo como** profesional de salud 
**Quiero** asignar metas a los pacientes que estoy tratando 
**Para** ayudar en su recuperación y seguimiento.

Tareas técnicas
- Crear campo para ingresar título de meta
- Crear campo para ingresar descripción de meta
- Crear dropdown para seleccionar categoría de meta
- Crear dropdown para seleccionar modalidad (diario, semanal, mensual) de meta
- Crear campo para ingresar la frecuencia de realización de la meta en una modalidad dada.
- Crear datepicker para seleccionar la fecha de inicio de la meta
- Crear datepicker para seleccionar la fecha límite de la meta
- Insertar meta en base de datos

Criterios de aceptación
- Poseer un campo de texto para ingresar un título a la meta.
- Poseer un campo de texto para ingresar una descripción de la meta.
- Poseer una lista desplegable para seleccionar la categoría a la cual corresponde la meta.
- Poseer un campo de texto si la categoría no se encuentra dentro de las opciones de la lista
- Después de completar el formulario, se debe poder guardar la meta asociada al paciente seleccionado.

**Comment by saltachin** [comment]
Hey! No es obligatorio, pero sería lindo si rellenan un poquito de los metadatos en este issue (iteración, estimación, prioridad, etc) para que el profe pueda verlo (y quizás calificarnos).

Gracias por la iniciativa.

**Comment by saltachin** [comment]
Y adicionalmente, si este borrador este listo, si gustan pueden pasarlo a la sección de Todo's (nomás para trackearlo, perdón si suena pedantic)

**Comment by lizethcorrales** [comment]
Listo!!

**Comment by saltachin** [comment]
Muchas gracias!
